<?php

/**
 * The file used to manage vardefs for Automizer actions
 *
 * LICENSE: The contents of this file are subject to the license agreement ("License") which is included
 * in the installation package (LICENSE.txt). By installing or using this file, you have unconditionally
 * agreed to the terms and conditions of the License, and you may not use this file except in compliance
 * with the License.
 *
 * @author     Biztech Consultancy
 */

$dictionary['bc_automizer_actions'] = array(
    'table' => 'bc_automizer_actions',
    'audited' => true,
    'activity_enabled' => false,
    'duplicate_merge' => true,
    'fields' => array(
        'recipient_type' =>
        array(
            'required' => false,
            'name' => 'recipient_type',
            'vname' => 'LBL_RECIPIENT_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 255,
            'dependency' => false,
        ),
        'recipient_module' =>
        array(
            'required' => false,
            'name' => 'recipient_module',
            'vname' => 'LBL_RECIPIENT_MODULE',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 255,
            'dependency' => false,
        ),
        'filter_by' =>
        array(
            'required' => false,
            'name' => 'filter_by',
            'vname' => 'LBL_FILTER_BY',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 255,
            'dependency' => false,
        ),
        'recipient_field' =>
        array(
            'required' => false,
            'name' => 'recipient_field',
            'vname' => 'LBL_RECIPIENT_FIELD',
            'type' => 'text',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 255,
            'dependency' => false,
        ),
        'recipient_operator' =>
        array(
            'required' => false,
            'name' => 'recipient_operator',
            'vname' => 'LBL_OPERATOR',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'options' => 'operator_list',
            'len' => 255,
            'dependency' => false,
        ),
        'compare_value' =>
        array(
            'required' => false,
            'name' => 'compare_value',
            'vname' => 'LBL_VALUE',
            'type' => 'text',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'dbType' => 'text',
            'dependency' => false,
        ),
        'recipient_email_field' =>
        array(
            'required' => false,
            'name' => 'recipient_email_field',
            'vname' => 'LBL_RECIPIENT_EMAIL_FIELD',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 255,
            'dependency' => false,
        ),
        'survey_id' =>
        array(
            'required' => false,
            'name' => 'survey_id',
            'vname' => 'LBL_SURVEY_ID',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 36,
            'dependency' => false,
        ),
        'email_template_id' =>
        array(
            'required' => false,
            'name' => 'email_template_id',
            'vname' => 'LBL_EMAIL_TEMPLATE_ID',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 36,
            'dependency' => false,
        ),
        'action_order' =>
        array(
            'required' => false,
            'name' => 'action_order',
            'vname' => 'LBL_ACTION_ORDER',
            'type' => 'int',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 255,
            'dependency' => false,
        ),
    ),
    'relationships' => array(
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
);

if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('bc_automizer_actions', 'bc_automizer_actions', array('basic', 'team_security', 'assignable'));
