<?php

/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

$dictionary['lev_CondicionesFinancieras'] = array(
    'table' => 'lev_condicionesfinancieras',
    'audited' => true,
    'activity_enabled' => false,
    'duplicate_merge' => true,
    'fields' => array (
  'idsolicitud' => 
  array (
    'required' => false,
    'name' => 'idsolicitud',
    'vname' => 'LBL_IDSOLICITUD',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '100',
    'size' => '20',
  ),
  'idactivo' => 
  array (
    'required' => false,
    'name' => 'idactivo',
    'vname' => 'LBL_IDACTIVO',
    'type' => 'enum',
    'massupdate' => true,
    'default' => '15558',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'idactivo_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'consecutivo' => 
  array (
    'required' => false,
    'name' => 'consecutivo',
    'vname' => 'LBL_CONSECUTIVO',
    'type' => 'int',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '100',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
  ),
  'plazo' => 
  array (
    'required' => false,
    'name' => 'plazo',
    'vname' => 'LBL_PLAZO',
    'type' => 'enum',
    'massupdate' => true,
    'default' => '1_12',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'plazo_0',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'plazo_minimo' => 
  array (
    'required' => false,
    'name' => 'plazo_minimo',
    'vname' => 'LBL_PLAZO_MINIMO',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '10',
    'size' => '20',
  ),
  'plazo_maximo' => 
  array (
    'required' => false,
    'name' => 'plazo_maximo',
    'vname' => 'LBL_PLAZO_MAXIMO',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '10',
    'size' => '20',
  ),
  'tasa_minima' => 
  array (
    'required' => false,
    'name' => 'tasa_minima',
    'vname' => 'LBL_TASA_MINIMA',
    'type' => 'decimal',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '5',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'tasa_maxima' => 
  array (
    'required' => false,
    'name' => 'tasa_maxima',
    'vname' => 'LBL_TASA_MAXIMA',
    'type' => 'decimal',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '5',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'vrc_minimo' => 
  array (
    'required' => false,
    'name' => 'vrc_minimo',
    'vname' => 'LBL_VRC_MINIMO',
    'type' => 'decimal',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '5',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'vrc_maximo' => 
  array (
    'required' => false,
    'name' => 'vrc_maximo',
    'vname' => 'LBL_VRC_MAXIMO',
    'type' => 'decimal',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '5',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'vri_minimo' => 
  array (
    'required' => false,
    'name' => 'vri_minimo',
    'vname' => 'LBL_VRI_MINIMO',
    'type' => 'decimal',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '5',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'vri_maximo' => 
  array (
    'required' => false,
    'name' => 'vri_maximo',
    'vname' => 'LBL_VRI_MAXIMO',
    'type' => 'decimal',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '5',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'deposito_en_garantia' => 
  array (
    'required' => false,
    'name' => 'deposito_en_garantia',
    'vname' => 'LBL_DEPOSITO_EN_GARANTIA',
    'type' => 'bool',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'comision_minima' => 
  array (
    'required' => false,
    'name' => 'comision_minima',
    'vname' => 'LBL_COMISION_MINIMA',
    'type' => 'decimal',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '5',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'comision_maxima' => 
  array (
    'required' => false,
    'name' => 'comision_maxima',
    'vname' => 'LBL_COMISION_MAXIMA',
    'type' => 'decimal',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '5',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'renta_inicial_minima' => 
  array (
    'required' => false,
    'name' => 'renta_inicial_minima',
    'vname' => 'LBL_RENTA_INICIAL_MINIMA',
    'type' => 'decimal',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '5',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'renta_inicial_maxima' => 
  array (
    'required' => false,
    'name' => 'renta_inicial_maxima',
    'vname' => 'LBL_RENTA_INICIAL_MAXIMA',
    'type' => 'decimal',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '5',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
  ),
  'uso_particular' => 
  array (
    'required' => false,
    'name' => 'uso_particular',
    'vname' => 'LBL_USO_PARTICULAR',
    'type' => 'bool',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'uso_empresarial' => 
  array (
    'required' => false,
    'name' => 'uso_empresarial',
    'vname' => 'LBL_USO_EMPRESARIAL',
    'type' => 'bool',
    'massupdate' => false,
    'default' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'activo_nuevo' => 
  array (
    'required' => false,
    'name' => 'activo_nuevo',
    'vname' => 'LBL_ACTIVO_NUEVO',
    'type' => 'bool',
    'massupdate' => false,
    'default' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'activo_usado' => 
  array (
    'required' => false,
    'name' => 'activo_usado',
    'vname' => 'LBL_ACTIVO_USADO',
    'type' => 'bool',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'incremento_ratificacion' => 
  array (
    'required' => false,
    'name' => 'incremento_ratificacion',
    'vname' => 'LBL_INCREMENTO_RATIFICACION',
    'type' => 'bool',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);

if (!class_exists('VardefManager')){
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('lev_CondicionesFinancieras','lev_CondicionesFinancieras', array('basic','team_security','assignable'));