<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN lev_CondicionesFinancieras
 */


class lev_CondicionesFinancieras_sugar extends Basic {
    public $new_schema = true;
    public $module_dir = 'lev_CondicionesFinancieras';
    public $object_name = 'lev_CondicionesFinancieras';
    public $table_name = 'lev_condicionesfinancieras';
    public $importable = true;
    public $team_id;
    public $team_set_id;
    public $team_count;
    public $team_name;
    public $team_link;
    public $team_count_link;
    public $teams;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $doc_owner;
    public $user_favorites;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $activities;
    public $following;
    public $following_link;
    public $my_favorite;
    public $favorite_link;
    public $idsolicitud;
    public $idactivo;
    public $consecutivo;
    public $plazo;
    public $plazo_minimo;
    public $plazo_maximo;
    public $tasa_minima;
    public $tasa_maxima;
    public $vrc_minimo;
    public $vrc_maximo;
    public $vri_minimo;
    public $vri_maximo;
    public $deposito_en_garantia;
    public $comision_minima;
    public $comision_maxima;
    public $renta_inicial_minima;
    public $renta_inicial_maxima;
    public $uso_particular;
    public $uso_empresarial;
    public $activo_nuevo;
    public $activo_usado;
    public $incremento_ratificacion;
    
    /**
     * This is a deprecated method, please start using __construct() as this
     * method will be removed in a future version.
     *
     * @see __construct
     * @deprecated
     */
    public function lev_CondicionesFinancieras_sugar(){
        $GLOBALS['log']->deprecated('Calls to lev_CondicionesFinancieras::lev_CondicionesFinancieras are deprecated.');
        self::__construct();
    }

    public function __construct(){
        parent::__construct();
    }
    
    public function bean_implements($interface){
        switch($interface){
            case 'ACL': return true;
        }
        return false;
    }
    
}