<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN uni_Productos
 */


class uni_Productos_sugar extends Basic {
    public $new_schema = true;
    public $module_dir = 'uni_Productos';
    public $object_name = 'uni_Productos';
    public $table_name = 'uni_productos';
    public $importable = false;
    public $team_id;
    public $team_set_id;
    public $acl_team_set_id;
    public $team_count;
    public $team_name;
    public $acl_team_names;
    public $team_link;
    public $team_count_link;
    public $teams;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $tag;
    public $tag_link;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $activities;
    public $following;
    public $following_link;
    public $my_favorite;
    public $favorite_link;
    public $commentlog;
    public $commentlog_link;
    public $locked_fields;
    public $locked_fields_link;
    public $tipo_producto;
    public $no_viable_razon;
    public $no_viable_razon_fp;
    public $no_viable_razon_cf;
    public $no_viable_producto;
    public $no_viable_razon_ni;
    public $tipo_cuenta;
    public $subtipo_cuenta;
    public $nps_calificacion;
    public $estatus_atencion;
    public $no_viable_quien;
    public $no_viable_porque;
    public $tipo_subtipo_cuenta;
    public $nps_comentario;
    public $no_viable;
    public $monto_impago;
    public $currency_id;
    public $base_rate;
    public $anexos_activos;
    public $anexos_historicos;
    public $fecha_pago;
    public $fecha_termino;
    public $fecha_impago;
    public $fecha_liberacion;
    public $nps_fecha;
    
    public function bean_implements($interface){
        switch($interface){
            case 'ACL': return true;
        }
        return false;
    }
    
}