<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN Cot_Cotizaciones
 */


class Cot_Cotizaciones_sugar extends Basic {
    public $new_schema = true;
    public $module_dir = 'Cot_Cotizaciones';
    public $object_name = 'Cot_Cotizaciones';
    public $table_name = 'cot_cotizaciones';
    public $importable = false;
    public $team_id;
    public $team_set_id;
    public $acl_team_set_id;
    public $team_count;
    public $team_name;
    public $acl_team_names;
    public $team_link;
    public $team_count_link;
    public $teams;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $tag;
    public $tag_link;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $activities;
    public $following;
    public $following_link;
    public $my_favorite;
    public $favorite_link;
    public $commentlog;
    public $commentlog_link;
    public $locked_fields;
    public $locked_fields_link;
    public $sync_key;
    public $statuscode;
    public $int_id_dynamics;
    public $int_indicativo;
    public $int_prima_neta;
    public $currency_id;
    public $base_rate;
    public $int_comision_porcentaje;
    public $int_comision;
    public $int_porcentaje_comision_total;
    public $int_porcentaje_sobrecomision;
    public $int_comision_documento;
    public $int_honorarios_fee;
    public $int_honorarios_fee_porcentaje;
    public $int_udi;
    public $int_reaseguro;
    public $int_coaseguro;
    
    public function bean_implements($interface){
        switch($interface){
            case 'ACL': return true;
        }
        return false;
    }
    
}