<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '7.9.3.0',
  'acceptable_sugar_versions' => 
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => 'TCT2',
  'author' => 'Tactos',
  'description' => 'Notificaciones',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Notificaciones',
  'published_date' => '2018-03-22 16:47:17',
  'type' => 'module',
  'version' => 1521737238,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Notificaciones',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'TCT2_Notificaciones',
      'class' => 'TCT2_Notificaciones',
      'path' => 'modules/TCT2_Notificaciones/TCT2_Notificaciones.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/tct2_notificaciones_accounts_Accounts.php',
      'to_module' => 'Accounts',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/tct2_notificaciones_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/tct2_notificaciones_users_Users.php',
      'to_module' => 'Users',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/tct2_notificaciones_accountsMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/tct2_notificaciones_opportunitiesMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/tct2_notificaciones_usersMetaData.php',
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/TCT2_Notificaciones',
      'to' => 'modules/TCT2_Notificaciones',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'bg_BG',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'cs_CZ',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'da_DK',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'de_DE',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'el_EL',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'es_ES',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'fr_FR',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'he_IL',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'hu_HU',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'it_it',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'lt_LT',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'ja_JP',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'ko_KR',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'lv_LV',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'nb_NO',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'nl_NL',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'pl_PL',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'pt_PT',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'ro_RO',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'ru_RU',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'sv_SE',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'tr_TR',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'zh_CN',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'pt_BR',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'ca_ES',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'en_UK',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'sr_RS',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'sk_SK',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'sq_AL',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'et_EE',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'es_LA',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'fi_FI',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'zh_TW',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'ar_SA',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'uk_UA',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'hr_HR',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'th_TH',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'en_us',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'bg_BG',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'cs_CZ',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'da_DK',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'de_DE',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'el_EL',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'es_ES',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'fr_FR',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'he_IL',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'hu_HU',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'it_it',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'lt_LT',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'ja_JP',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'ko_KR',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'lv_LV',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'nb_NO',
    ),
    54 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'nl_NL',
    ),
    55 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'pl_PL',
    ),
    56 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'pt_PT',
    ),
    57 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'ro_RO',
    ),
    58 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'ru_RU',
    ),
    59 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'sv_SE',
    ),
    60 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'tr_TR',
    ),
    61 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'zh_CN',
    ),
    62 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'pt_BR',
    ),
    63 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'ca_ES',
    ),
    64 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'en_UK',
    ),
    65 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'sr_RS',
    ),
    66 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'sk_SK',
    ),
    67 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'sq_AL',
    ),
    68 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'et_EE',
    ),
    69 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'es_LA',
    ),
    70 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'fi_FI',
    ),
    71 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'zh_TW',
    ),
    72 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'ar_SA',
    ),
    73 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'uk_UA',
    ),
    74 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'hr_HR',
    ),
    75 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'th_TH',
    ),
    76 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'en_us',
    ),
    77 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'bg_BG',
    ),
    78 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'cs_CZ',
    ),
    79 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'da_DK',
    ),
    80 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'de_DE',
    ),
    81 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'el_EL',
    ),
    82 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'es_ES',
    ),
    83 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'fr_FR',
    ),
    84 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'he_IL',
    ),
    85 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'hu_HU',
    ),
    86 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'it_it',
    ),
    87 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'lt_LT',
    ),
    88 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ja_JP',
    ),
    89 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ko_KR',
    ),
    90 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'lv_LV',
    ),
    91 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'nb_NO',
    ),
    92 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'nl_NL',
    ),
    93 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'pl_PL',
    ),
    94 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'pt_PT',
    ),
    95 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ro_RO',
    ),
    96 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ru_RU',
    ),
    97 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'sv_SE',
    ),
    98 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'tr_TR',
    ),
    99 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'zh_CN',
    ),
    100 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'pt_BR',
    ),
    101 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ca_ES',
    ),
    102 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'en_UK',
    ),
    103 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'sr_RS',
    ),
    104 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'sk_SK',
    ),
    105 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'sq_AL',
    ),
    106 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'et_EE',
    ),
    107 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'es_LA',
    ),
    108 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'fi_FI',
    ),
    109 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'zh_TW',
    ),
    110 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ar_SA',
    ),
    111 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'uk_UA',
    ),
    112 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'hr_HR',
    ),
    113 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'th_TH',
    ),
    114 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'en_us',
    ),
    115 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'bg_BG',
    ),
    116 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'cs_CZ',
    ),
    117 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'da_DK',
    ),
    118 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'de_DE',
    ),
    119 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'el_EL',
    ),
    120 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'es_ES',
    ),
    121 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'fr_FR',
    ),
    122 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'he_IL',
    ),
    123 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'hu_HU',
    ),
    124 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'it_it',
    ),
    125 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'lt_LT',
    ),
    126 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'ja_JP',
    ),
    127 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'ko_KR',
    ),
    128 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'lv_LV',
    ),
    129 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'nb_NO',
    ),
    130 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'nl_NL',
    ),
    131 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'pl_PL',
    ),
    132 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'pt_PT',
    ),
    133 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'ro_RO',
    ),
    134 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'ru_RU',
    ),
    135 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'sv_SE',
    ),
    136 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'tr_TR',
    ),
    137 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'zh_CN',
    ),
    138 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'pt_BR',
    ),
    139 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'ca_ES',
    ),
    140 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'en_UK',
    ),
    141 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'sr_RS',
    ),
    142 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'sk_SK',
    ),
    143 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'sq_AL',
    ),
    144 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'et_EE',
    ),
    145 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'es_LA',
    ),
    146 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'fi_FI',
    ),
    147 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'zh_TW',
    ),
    148 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'ar_SA',
    ),
    149 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'uk_UA',
    ),
    150 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'hr_HR',
    ),
    151 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'th_TH',
    ),
    152 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'en_us',
    ),
    153 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'bg_BG',
    ),
    154 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'cs_CZ',
    ),
    155 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'da_DK',
    ),
    156 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'de_DE',
    ),
    157 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'el_EL',
    ),
    158 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'es_ES',
    ),
    159 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'fr_FR',
    ),
    160 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'he_IL',
    ),
    161 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'hu_HU',
    ),
    162 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'it_it',
    ),
    163 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'lt_LT',
    ),
    164 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ja_JP',
    ),
    165 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ko_KR',
    ),
    166 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'lv_LV',
    ),
    167 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'nb_NO',
    ),
    168 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'nl_NL',
    ),
    169 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'pl_PL',
    ),
    170 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'pt_PT',
    ),
    171 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ro_RO',
    ),
    172 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ru_RU',
    ),
    173 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'sv_SE',
    ),
    174 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'tr_TR',
    ),
    175 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'zh_CN',
    ),
    176 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'pt_BR',
    ),
    177 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ca_ES',
    ),
    178 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'en_UK',
    ),
    179 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'sr_RS',
    ),
    180 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'sk_SK',
    ),
    181 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'sq_AL',
    ),
    182 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'et_EE',
    ),
    183 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'es_LA',
    ),
    184 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'fi_FI',
    ),
    185 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'zh_TW',
    ),
    186 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'ar_SA',
    ),
    187 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'uk_UA',
    ),
    188 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'hr_HR',
    ),
    189 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'th_TH',
    ),
    190 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'en_us',
    ),
    191 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'bg_BG',
    ),
    192 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'cs_CZ',
    ),
    193 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'da_DK',
    ),
    194 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'de_DE',
    ),
    195 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'el_EL',
    ),
    196 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'es_ES',
    ),
    197 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'fr_FR',
    ),
    198 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'he_IL',
    ),
    199 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'hu_HU',
    ),
    200 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'it_it',
    ),
    201 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'lt_LT',
    ),
    202 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'ja_JP',
    ),
    203 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'ko_KR',
    ),
    204 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'lv_LV',
    ),
    205 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'nb_NO',
    ),
    206 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'nl_NL',
    ),
    207 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'pl_PL',
    ),
    208 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'pt_PT',
    ),
    209 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'ro_RO',
    ),
    210 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'ru_RU',
    ),
    211 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'sv_SE',
    ),
    212 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'tr_TR',
    ),
    213 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'zh_CN',
    ),
    214 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'pt_BR',
    ),
    215 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'ca_ES',
    ),
    216 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'en_UK',
    ),
    217 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'sr_RS',
    ),
    218 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'sk_SK',
    ),
    219 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'sq_AL',
    ),
    220 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'et_EE',
    ),
    221 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'es_LA',
    ),
    222 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'fi_FI',
    ),
    223 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'zh_TW',
    ),
    224 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'ar_SA',
    ),
    225 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'uk_UA',
    ),
    226 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'hr_HR',
    ),
    227 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
      'language' => 'th_TH',
    ),
    228 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/es_LA.lang.php',
      'to_module' => 'application',
      'language' => 'es_LA',
    ),
    229 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'sidecar' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/clients/base/layouts/subpanels/tct2_notificaciones_accounts_Accounts.php',
      'to_module' => 'Accounts',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/clients/base/layouts/subpanels/tct2_notificaciones_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/clients/mobile/layouts/subpanels/tct2_notificaciones_accounts_Accounts.php',
      'to_module' => 'Accounts',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/clients/mobile/layouts/subpanels/tct2_notificaciones_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/tct2_notificaciones_accounts_Accounts.php',
      'to_module' => 'Accounts',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/tct2_notificaciones_accounts_TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/tct2_notificaciones_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/tct2_notificaciones_opportunities_TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/tct2_notificaciones_users_Users.php',
      'to_module' => 'Users',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/tct2_notificaciones_users_TCT2_Notificaciones.php',
      'to_module' => 'TCT2_Notificaciones',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
  'wireless_subpanels' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/tct2_notificaciones_accounts_Accounts.php',
      'to_module' => 'Accounts',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/tct2_notificaciones_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/tct2_notificaciones_users_Users.php',
      'to_module' => 'Users',
    ),
  ),
  'image_dir' => '<basepath>/icons',
);