<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '7.5.2.1',
  'acceptable_sugar_versions' => 
  array (
    0 => '7.5.2.1',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => 'TCT1',
  'author' => 'Salvador López',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'project_Personas_Fideicomiso',
  'published_date' => '2017-12-22 15:48:47',
  'type' => 'module',
  'version' => 1513957727,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'project_Personas_Fideicomiso',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/Personas_Fideicomiso',
      'to' => 'custom/modulebuilder/packages/Personas_Fideicomiso',
    ),
  ),
);