<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '7.9.3.0',
  'acceptable_sugar_versions' => 
  array (
    0 => '7.9.3.0',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => 'tct02',
  'author' => 'Tactos',
  'description' => 'Módulo de resumen para personas en vista 360',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'project_ResumenPersonas',
  'published_date' => '2018-03-06 00:17:05',
  'type' => 'module',
  'version' => 1520295426,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'project_ResumenPersonas',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/ResumenPersonas',
      'to' => 'custom/modulebuilder/packages/ResumenPersonas',
    ),
  ),
);