<?php
// created: 2019-11-27 12:43:01
$dictionary["Opportunity"]["fields"]["opportunities_opportunities_2"] = array (
  'name' => 'opportunities_opportunities_2',
  'type' => 'link',
  'relationship' => 'opportunities_opportunities_2',
  'source' => 'non-db',
  'module' => 'Opportunities',
  'bean_name' => 'Opportunity',
  'vname' => 'LBL_OPPORTUNITIES_OPPORTUNITIES_2_FROM_OPPORTUNITIES_L_TITLE',
  'id_name' => 'opportunities_opportunities_2opportunities_ida',
);
$dictionary["Opportunity"]["fields"]["opportunities_opportunities_2"] = array (
  'name' => 'opportunities_opportunities_2',
  'type' => 'link',
  'relationship' => 'opportunities_opportunities_2',
  'source' => 'non-db',
  'module' => 'Opportunities',
  'bean_name' => 'Opportunity',
  'vname' => 'LBL_OPPORTUNITIES_OPPORTUNITIES_2_FROM_OPPORTUNITIES_R_TITLE',
  'id_name' => 'opportunities_opportunities_2opportunities_ida',
);
$dictionary["Opportunity"]["fields"]["opportunities_opportunities_2_name"] = array (
  'name' => 'opportunities_opportunities_2_name',
  'type' => 'relate',
  'source' => 'non-db',
  'vname' => 'LBL_OPPORTUNITIES_OPPORTUNITIES_2_FROM_OPPORTUNITIES_R_TITLE',
  'save' => true,
  'id_name' => 'opportunities_opportunities_2opportunities_ida',
  'link' => 'opportunities_opportunities_2',
  'table' => 'opportunities',
  'module' => 'Opportunities',
  'rname' => 'name',
);
$dictionary["Opportunity"]["fields"]["opportunities_opportunities_2_name"] = array (
  'name' => 'opportunities_opportunities_2_name',
  'type' => 'relate',
  'source' => 'non-db',
  'vname' => 'LBL_OPPORTUNITIES_OPPORTUNITIES_2_FROM_OPPORTUNITIES_L_TITLE',
  'save' => true,
  'id_name' => 'opportunities_opportunities_2opportunities_ida',
  'link' => 'opportunities_opportunities_2',
  'table' => 'opportunities',
  'module' => 'Opportunities',
  'rname' => 'name',
);
$dictionary["Opportunity"]["fields"]["opportunities_opportunities_2opportunities_ida"] = array (
  'name' => 'opportunities_opportunities_2opportunities_ida',
  'type' => 'id',
  'source' => 'non-db',
  'vname' => 'LBL_OPPORTUNITIES_OPPORTUNITIES_2_FROM_OPPORTUNITIES_R_TITLE_ID',
  'id_name' => 'opportunities_opportunities_2opportunities_ida',
  'link' => 'opportunities_opportunities_2',
  'table' => 'opportunities',
  'module' => 'Opportunities',
  'rname' => 'id',
  'reportable' => false,
  'side' => 'left',
  'massupdate' => false,
  'duplicate_merge' => 'disabled',
  'hideacl' => true,
);
$dictionary["Opportunity"]["fields"]["opportunities_opportunities_2opportunities_ida"] = array (
  'name' => 'opportunities_opportunities_2opportunities_ida',
  'type' => 'id',
  'source' => 'non-db',
  'vname' => 'LBL_OPPORTUNITIES_OPPORTUNITIES_2_FROM_OPPORTUNITIES_L_TITLE_ID',
  'id_name' => 'opportunities_opportunities_2opportunities_ida',
  'link' => 'opportunities_opportunities_2',
  'table' => 'opportunities',
  'module' => 'Opportunities',
  'rname' => 'id',
  'reportable' => false,
  'side' => 'left',
  'massupdate' => false,
  'duplicate_merge' => 'disabled',
  'hideacl' => true,
);
