<?php

/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

$dictionary['Rel_Relaciones'] = array(
    'table' => 'rel_relaciones',
    'audited' => true,
    'activity_enabled' => false,
    'duplicate_merge' => true,
    'fields' => array (
  'inactivo' => 
  array (
    'required' => false,
    'name' => 'inactivo',
    'vname' => 'LBL_INACTIVO',
    'type' => 'bool',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tipodecontacto' => 
  array (
    'required' => false,
    'name' => 'tipodecontacto',
    'vname' => 'LBL_TIPODECONTACTO',
    'type' => 'enum',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'Tipo_Contacto_list',
    'studio' => 'visible',
    'dependency' => 'or(equal($relacionesactivas,"Accionista"),equal($relacionesinactivas,"Contacto"))',
  ),
  'participacion' => 
  array (
    'required' => false,
    'name' => 'participacion',
    'vname' => 'LBL_PARTICIPACION',
    'type' => 'decimal',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '3',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
    'dependency' => 'or(equal($relacionesactivas,"Accionista"),equal($relacionesinactivas,"Accionista"))',
  ),
  'miembrodecomite' => 
  array (
    'required' => false,
    'name' => 'miembrodecomite',
    'vname' => 'LBL_MIEMBRODECOMITE',
    'type' => 'bool',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'dependency' => 'or(equal($relacionesactivas,"Accionista"),equal($relacionesinactivas,"Accionista"))',
  ),
  'montodeparticipacion' => 
  array (
    'required' => false,
    'name' => 'montodeparticipacion',
    'vname' => 'LBL_MONTODEPARTICIPACION',
    'type' => 'currency',
    'massupdate' => false,
    'default' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
    'related_fields' => 
    array (
      0 => 'currency_id',
      1 => 'base_rate',
    ),
    'dependency' => 'or(equal($relacionesactivas,"Accionista"),equal($relacionesinactivas,"Accionista"))',
  ),
  'currency_id' => 
  array (
    'required' => false,
    'name' => 'currency_id',
    'vname' => 'LBL_CURRENCY_ID',
    'type' => 'currency_id',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => 1,
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 36,
    'size' => '20',
    'dbType' => 'id',
    'studio' => 'visible',
    'function' => 'getCurrencies',
    'function_bean' => 'Currencies',
  ),
  'base_rate' => 
  array (
    'required' => false,
    'name' => 'base_rate',
    'vname' => 'LBL_CURRENCY_RATE',
    'type' => 'decimal',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => 1,
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
    'label' => 'LBL_CURRENCY_RATE',
    'studio' => false,
  ),
  'tiempodeconocerloano' => 
  array (
    'required' => false,
    'name' => 'tiempodeconocerloano',
    'vname' => 'LBL_TIEMPODECONOCERLOANO',
    'type' => 'int',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '100',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
    'dependency' => 'or(equal($relacionesactivas,"Accionista"),equal($relacionesinactivas,"Referencia"))',
  ),
  'tiempodeconocerlomeses' => 
  array (
    'required' => false,
    'name' => 'tiempodeconocerlomeses',
    'vname' => 'LBL_TIEMPODECONOCERLOMESES',
    'type' => 'int',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '100',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
    'dependency' => 'or(equal($relacionesactivas,"Accionista"),equal($relacionesinactivas,"Referencia"))',
  ),
  'parentesco' => 
  array (
    'required' => false,
    'name' => 'parentesco',
    'vname' => 'LBL_PARENTESCO',
    'type' => 'enum',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'Parentesco_list',
    'studio' => 'visible',
    'dependency' => 'or(equal($relacionesactivas,"Accionista"),equal($relacionesinactivas,"Referencia Personal"))',
  ),
  'plazocredito' => 
  array (
    'required' => false,
    'name' => 'plazocredito',
    'vname' => 'LBL_PLAZOCREDITO',
    'type' => 'int',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '100',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
    'dependency' => 'or(equal($relacionesactivas,"Accionista"),equal($relacionesinactivas,"Referencia Cliente"))',
  ),
  'facturacionmensual' => 
  array (
    'required' => false,
    'name' => 'facturacionmensual',
    'vname' => 'LBL_FACTURACIONMENSUAL',
    'type' => 'currency',
    'massupdate' => false,
    'default' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
    'related_fields' => 
    array (
      0 => 'currency_id',
      1 => 'base_rate',
    ),
    'dependency' => 'or(equal($relacionesactivas,"Accionista"),equal($relacionesinactivas,"Referencia Cliente"))',
  ),
  'probabilidadincremento' => 
  array (
    'required' => false,
    'name' => 'probabilidadincremento',
    'vname' => 'LBL_PROBABILIDADINCREMENTO',
    'type' => 'decimal',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '3',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '2',
    'dependency' => 'or(equal($relacionesactivas,"Accionista"),equal($relacionesinactivas,"Referencia Cliente"))',
  ),
  'opinion' => 
  array (
    'required' => false,
    'name' => 'opinion',
    'vname' => 'LBL_OPINION',
    'type' => 'enum',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'Opinion_Ref_list',
    'studio' => 'visible',
    'dependency' => 'or(equal($relacionesactivas,"Accionista"),equal($relacionesinactivas,"Referencia Cliente or Proveedor"))',
  ),
  'linea' => 
  array (
    'required' => false,
    'name' => 'linea',
    'vname' => 'LBL_LINEA',
    'type' => 'currency',
    'massupdate' => false,
    'default' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
    'related_fields' => 
    array (
      0 => 'currency_id',
      1 => 'base_rate',
    ),
    'dependency' => 'or(equal($relacionesactivas,"Accionista"),equal($relacionesinactivas,"Referencia Proveedor"))',
  ),
  'saldo' => 
  array (
    'required' => false,
    'name' => 'saldo',
    'vname' => 'LBL_SALDO',
    'type' => 'currency',
    'massupdate' => false,
    'default' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
    'related_fields' => 
    array (
      0 => 'currency_id',
      1 => 'base_rate',
    ),
    'dependency' => 'or(equal($relacionesactivas,"Accionista"),equal($relacionesinactivas,"Referencia Proveedor"))',
  ),
  'consumomensual' => 
  array (
    'required' => false,
    'name' => 'consumomensual',
    'vname' => 'LBL_CONSUMOMENSUAL',
    'type' => 'currency',
    'massupdate' => false,
    'default' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
    'related_fields' => 
    array (
      0 => 'currency_id',
      1 => 'base_rate',
    ),
    'dependency' => 'or(equal($relacionesactivas,"Accionista"),equal($relacionesinactivas,"Referencia Proveedor"))',
  ),
  'producto' => 
  array (
    'required' => false,
    'name' => 'producto',
    'vname' => 'LBL_PRODUCTO',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '100',
    'size' => '20',
    'dependency' => 'or(equal($relacionesactivas,"Accionista"),equal($relacionesinactivas,"Referencia Proveedor"))',
  ),
  'limitedecredito' => 
  array (
    'required' => false,
    'name' => 'limitedecredito',
    'vname' => 'LBL_LIMITEDECREDITO',
    'type' => 'currency',
    'massupdate' => false,
    'default' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
    'related_fields' => 
    array (
      0 => 'currency_id',
      1 => 'base_rate',
    ),
    'dependency' => 'or(equal($relacionesactivas,"Accionista"),equal($relacionesinactivas,"Referencia Proveedor"))',
  ),
  'plazoendias' => 
  array (
    'required' => false,
    'name' => 'plazoendias',
    'vname' => 'LBL_PLAZOENDIAS',
    'type' => 'int',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '50',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
    'dependency' => 'or(equal($relacionesactivas,"Accionista"),equal($relacionesinactivas,"Referencia Proveedor"))',
  ),
  'puesto' => 
  array (
    'required' => false,
    'name' => 'puesto',
    'vname' => 'LBL_PUESTO',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '50',
    'size' => '20',
    'dependency' => 'or(equal($relacionesactivas,"Accionista"),equal($relacionesinactivas,"Representante"))',
  ),
  'puestodescription' => 
  array (
    'required' => false,
    'name' => 'puestodescription',
    'vname' => 'LBL_PUESTODESCRIPTION',
    'type' => 'text',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
    'dependency' => 'or(equal($relacionesactivas,"Accionista"),equal($relacionesinactivas,"Representante"))',
  ),
  'verificaciondereferencia' => 
  array (
    'required' => false,
    'name' => 'verificaciondereferencia',
    'vname' => 'LBL_VERIFICACIONDEREFERENCIA',
    'type' => 'enum',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'verificaciondereferencia_list',
    'studio' => 'visible',
    'dependency' => 'or(equal($relacionesactivas,"Accionista"),equal($relacionesinactivas,"Referencia"))',
  ),
  'relaciones_activas' => 
  array (
    'required' => false,
    'name' => 'relaciones_activas',
    'vname' => 'LBL_RELACIONES_ACTIVAS',
    'type' => 'multienum',
    'massupdate' => true,
    'default' => '^^',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'size' => '20',
    'options' => 'Relaciones_Activas_list',
    'studio' => 'visible',
    'dependency' => '',
    'isMultiSelect' => true,
  ),
  'relaciones_inactivas' => 
  array (
    'required' => false,
    'name' => 'relaciones_inactivas',
    'vname' => 'LBL_RELACIONES_INACTIVAS',
    'type' => 'multienum',
    'massupdate' => true,
    'default' => '^^',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'size' => '20',
    'options' => 'Relaciones_Activas_list',
    'studio' => 'visible',
    'dependency' => '',
    'isMultiSelect' => true,
  ),
),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);

if (!class_exists('VardefManager')){
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('Rel_Relaciones','Rel_Relaciones', array('basic','team_security','assignable'));