<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '10.0.2',
  'acceptable_sugar_versions' => 
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => 'tct4',
  'author' => 'Tactos',
  'description' => 'Condiciones de una cuenta a operar por parte de Cartera, Crédito, Comercial y Cumplimiento',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Condiciones',
  'published_date' => '2021-05-27 17:56:41',
  'type' => 'module',
  'version' => 1622138201,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Condiciones',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'tct4_Condiciones',
      'class' => 'tct4_Condiciones',
      'path' => 'modules/tct4_Condiciones/tct4_Condiciones.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/tct4_Condiciones',
      'to' => 'modules/tct4_Condiciones',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/es_LA.lang.php',
      'to_module' => 'application',
      'language' => 'es_LA',
    ),
  ),
  'image_dir' => '<basepath>/icons',
);