<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN uni_Brujula
 */


class uni_Brujula_sugar extends Basic {
    public $new_schema = true;
    public $module_dir = 'uni_Brujula';
    public $object_name = 'uni_Brujula';
    public $table_name = 'uni_brujula';
    public $importable = true;
    public $team_id;
    public $team_set_id;
    public $team_count;
    public $team_name;
    public $team_link;
    public $team_count_link;
    public $teams;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $doc_owner;
    public $user_favorites;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $activities;
    public $following;
    public $following_link;
    public $my_favorite;
    public $favorite_link;
    public $id_brujula;
    public $fecha_reporte;
    public $extemporaneo;
    public $contactos_numero;
    public $contactos_duracion;
    public $contactos_no_localizados;
    public $contactos_no_interesados;
    public $contactos_seguimiento_futuro;
    public $contactos_siguiente_llamada;
    public $contactos_por_visitar;
    public $contactos_enviaran_informacion;
    public $tiempo_prospeccion;
    public $tiempo_armado_expedientes;
    public $tiempo_seguimiento_expedientes;
    public $tiempo_operacion;
    public $tiempo_liberacion;
    public $tiempo_servicio_cliente;
    public $tiempo_otras_actividades;
    public $tiempo_total;
    public $porcentaje_prospeccion;
    public $porcentaje_armado_expedientes;
    public $porcentaje_seguimiento_expedie;
    public $porcentaje_operacion;
    public $porcentaje_liberacion;
    public $porcentaje_servicio_cliente;
    public $porcentaje_otras_actividades;
    
    /**
     * This is a deprecated method, please start using __construct() as this
     * method will be removed in a future version.
     *
     * @see __construct
     * @deprecated
     */
    public function uni_Brujula_sugar(){
        $GLOBALS['log']->deprecated('Calls to uni_Brujula::uni_Brujula are deprecated.');
        self::__construct();
    }

    public function __construct(){
        parent::__construct();
    }
    
    public function bean_implements($interface){
        switch($interface){
            case 'ACL': return true;
        }
        return false;
    }
    
}