<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '7.9.3.0',
  'acceptable_sugar_versions' => 
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => 'tct02',
  'author' => 'Tactos',
  'description' => 'Módulo de resumen para personas en vista 360',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'ResumenPersonas',
  'published_date' => '2018-03-06 00:22:01',
  'type' => 'module',
  'version' => 1520295721,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'ResumenPersonas',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'tct02_Resumen',
      'class' => 'tct02_Resumen',
      'path' => 'modules/tct02_Resumen/tct02_Resumen.php',
      'tab' => false,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/tct02_Resumen',
      'to' => 'modules/tct02_Resumen',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/es_LA.lang.php',
      'to_module' => 'application',
      'language' => 'es_LA',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'image_dir' => '<basepath>/icons',
);