<?php

/* This file was generated by the 7_FixIconNameChanges upgrader */
$viewdefs['lev_CondicionesFinancieras']['base']['menu']['header'] =  array (
  0 => 
  array (
    'route' => '#lev_CondicionesFinancieras/create',
    'label' => 'LNK_NEW_RECORD',
    'acl_action' => 'create',
    'acl_module' => 'lev_CondicionesFinancieras',
    'icon' => 'fa-plus',
  ),
  1 => 
  array (
    'route' => '#lev_CondicionesFinancieras',
    'label' => 'LNK_LIST',
    'acl_action' => 'list',
    'acl_module' => 'lev_CondicionesFinancieras',
    'icon' => 'fa-bars',
  ),
  2 => 
  array (
    'route' => '#bwc/index.php?module=Import&action=Step1&import_module=lev_CondicionesFinancieras&return_module=lev_CondicionesFinancieras&return_action=index',
    'label' => 'LBL_IMPORT',
    'acl_action' => 'import',
    'acl_module' => 'lev_CondicionesFinancieras',
    'icon' => 'fa-upload',
  ),
);
