<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN lev_Backlog
 */


class lev_Backlog_sugar extends Basic {
    public $new_schema = true;
    public $module_dir = 'lev_Backlog';
    public $object_name = 'lev_Backlog';
    public $table_name = 'lev_backlog';
    public $importable = true;
    public $team_id;
    public $team_set_id;
    public $team_count;
    public $team_name;
    public $team_link;
    public $team_count_link;
    public $teams;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $doc_owner;
    public $user_favorites;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $activities;
    public $following;
    public $following_link;
    public $my_favorite;
    public $favorite_link;
    public $producto;
    public $account_id_c;
    public $cliente;
    public $monto_comprometido;
    public $currency_id;
    public $base_rate;
    public $monto_real_logrado;
    public $etapa;
    public $mes;
    public $anio;
    public $numero_de_backlog;
    public $numero_de_solicitud;
    public $estatus_de_la_operacion;
    public $tipo_de_operacion;
    public $tipo;
    public $renta_inicial_comprometida;
    public $renta_inicial_real;
    public $region;
    public $monto_original;
    public $monto_comprometido_cancelado;
    public $renta_inicialcomp_can;
    public $motivo_de_cancelacion;
    public $etapa_preliminar;
    public $progreso;
    public $editar;
    public $equipo;
    public $comentario;
    public $activo;
    
    /**
     * This is a deprecated method, please start using __construct() as this
     * method will be removed in a future version.
     *
     * @see __construct
     * @deprecated
     */
    public function lev_Backlog_sugar(){
        $GLOBALS['log']->deprecated('Calls to lev_Backlog::lev_Backlog are deprecated.');
        self::__construct();
    }

    public function __construct(){
        parent::__construct();
    }
    
    public function bean_implements($interface){
        switch($interface){
            case 'ACL': return true;
        }
        return false;
    }
    
}