<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
   'acceptable_sugar_flavors' => array('PRO','ENT','ULT'),
    'acceptable_sugar_versions' => array(
        'exact_matches' => array(),
        'regex_matches' => array('10.*.*','11.*.*'),
    ),
  'readme' => '',
  'key' => 'Soft',
  'author' => 'SoftPhone',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'cti-connector-sugar-entities',
  'published_date' => '2016-05-31 09:19:27',
  'type' => 'module',
  'version' => '2.5.0',
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'cti-connector-sugar-entities',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SoftPhone_WDE_Connector_Core',
      'to' => 'custom/modulebuilder/packages/SoftPhoneEntities',
    ),
  ),
);