<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '11.0.2',
  'acceptable_sugar_versions' => 
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => 'Soft',
  'author' => 'SoftPhone',
  'description' => 'Load WDE Connector custom SugarCRM entities',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'SoftPhoneEntities',
  'published_date' => '2022-03-24 18:44:58',
  'type' => 'module',
  'version' => 1648147522,
  'remove_tables' => 'prompt',
);

