<?php

/* This file was generated by the 7_FixIconNameChanges upgrader */
$viewdefs['emp_empleo']['base']['menu']['header'] =  array (
  0 => 
  array (
    'route' => '#emp_empleo/create',
    'label' => 'LNK_NEW_RECORD',
    'acl_action' => 'create',
    'acl_module' => 'emp_empleo',
    'icon' => 'fa-plus',
  ),
  1 => 
  array (
    'route' => '#emp_empleo',
    'label' => 'LNK_LIST',
    'acl_action' => 'list',
    'acl_module' => 'emp_empleo',
    'icon' => 'fa-bars',
  ),
  2 => 
  array (
    'route' => '#bwc/index.php?module=Import&action=Step1&import_module=emp_empleo&return_module=emp_empleo&return_action=index',
    'label' => 'LBL_IMPORT',
    'acl_action' => 'import',
    'acl_module' => 'emp_empleo',
    'icon' => 'fa-upload',
  ),
);
