<?php

/**
 * The file used to handle fields definition for survey answers
 *
 * LICENSE: The contents of this file are subject to the license agreement ("License") which is included
 * in the installation package (LICENSE.txt). By installing or using this file, you have unconditionally
 * agreed to the terms and conditions of the License, and you may not use this file except in compliance
 * with the License.
 *
 * @author     Biztech Consultancy
 */
$dictionary['bc_survey_submission'] = array(
    'table' => 'bc_survey_submission',
    'audited' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'last_send_on' =>
        array(
            'required' => false,
            'name' => 'last_send_on',
            'vname' => 'LBL_LAST_SEND_ON',
            'type' => 'datetimecombo',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => false,
            'dbType' => 'datetime',
        ),
        'submission_date' =>
        array(
            'required' => false,
            'name' => 'submission_date',
            'vname' => 'LBL_SUBMISSION_DATE',
            'type' => 'datetimecombo',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => false,
            'dbType' => 'datetime',
        ),
        'email_opened' =>
        array(
            'required' => false,
            'name' => 'email_opened',
            'vname' => 'LBL_EMAIL_OPENED',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '0',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
        ),
        'survey_send' =>
        array(
            'required' => false,
            'name' => 'survey_send',
            'vname' => 'LBL_SURVEY_SEND',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '0',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
        ),
        'schedule_on' =>
        array(
            'required' => false,
            'name' => 'schedule_on',
            'vname' => 'LBL_SCHEDULE_ON',
            'type' => 'datetimecombo',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => false,
            'dbType' => 'datetime',
        ),
        'status' =>
        array(
            'required' => false,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => 0,
            'default' => 'Pending',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'survey_submission_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'customer_name' =>
        array(
            'required' => false,
            'name' => 'customer_name',
            'vname' => 'LBL_CUSTOMER_NAME',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
        ),
        'resubmit' =>
        array(
            'required' => false,
            'name' => 'resubmit',
            'vname' => 'LBL_RESUBMIT',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '0',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
        ),
        'resubmit_counter' =>
        array(
            'required' => false,
            'name' => 'resubmit_counter',
            'vname' => 'LBL_RESUBMIT_NUMBER',
            'type' => 'int',
            'len' => 11,
            'default' => 0,
            'isnull' => 'false',
            'unified_search' => true,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'reportable' => true,
            'disable_num_format' => true,
        ),
        'change_request' =>
        array(
            'required' => false,
            'name' => 'change_request',
            'vname' => 'LBL_CHANGE_REQUEST',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'default' => 'N/A',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '25',
        ),
        'resend' =>
        array(
            'required' => false,
            'name' => 'resend',
            'vname' => 'LBL_RESEND',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '0',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
        ),
        'resend_counter' =>
        array(
            'required' => false,
            'name' => 'resend_counter',
            'vname' => 'LBL_RESEND_NUMBER',
            'type' => 'int',
            'len' => 11,
            'default' => 0,
            'isnull' => 'false',
            'unified_search' => true,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'reportable' => true,
            'disable_num_format' => true,
        ),
        'submitted_by' =>
        array(
            'required' => false,
            'name' => 'submitted_by',
            'vname' => 'LBL_SUBMITTED_BY',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'options' => 'submitted_by',
            'default' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
        ),
        'recipient_as' =>
        array(
            'required' => false,
            'name' => 'recipient_as',
            'vname' => 'LBL_RECIPIENT_AS',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'default' => 'to',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '25',
        ),
        'mail_status' =>
        array(
            'required' => false,
            'name' => 'mail_status',
            'vname' => 'LBL_MAIL_STATUS',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '999',
        ),
        'base_score' =>
        array(
            'required' => false,
            'name' => 'base_score',
            'vname' => 'LBL_BASE_SCORE',
            'type' => 'int',
            'len' => 11,
            'default' => 0,
            'isnull' => 'false',
            'unified_search' => true,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'reportable' => true,
            'disable_num_format' => true,
        ),
        'obtained_score' =>
        array(
            'required' => false,
            'name' => 'obtained_score',
            'vname' => 'LBL_OBTAINED_SCORE',
            'type' => 'int',
            'len' => 11,
            'default' => 0,
            'isnull' => 'false',
            'unified_search' => true,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'reportable' => true,
            'disable_num_format' => true,
        ),
        'score_percentage' =>
        array(
            'required' => false,
            'name' => 'score_percentage',
            'vname' => 'LBL_SCORE_PERCENTAGE',
            'type' => 'int',
            'len' => 11,
            'default' => 0,
            'isnull' => 'false',
            'unified_search' => true,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'reportable' => true,
            'disable_num_format' => true,
        ),
        'parent_type' =>
        array(
            'name' => 'parent_type',
            'vname' => 'LBL_ORIGIN_PARENT_NAME',
            'type' => 'parent_type',
            'dbType' => 'varchar',
            'group' => 'parent_name',
            'options' => 'origin_parent_type_survey_display',
            'required' => false,
            'len' => '255',
            'comment' => 'The Sugar object to which the call is related',
            'studio' => array('wirelesslistview' => false),
        ),
        'parent_name' =>
        array(
            'name' => 'parent_name',
            'parent_type' => 'record_type_display',
            'type_name' => 'parent_type',
            'id_name' => 'parent_id',
            'vname' => 'LBL_ORIGIN_LIST_RELATED_TO',
            'type' => 'parent',
            'group' => 'parent_name',
            'source' => 'non-db',
            'options' => 'origin_parent_type_survey_display',
            'studio' => true,
        ),
        'parent_id' =>
        array(
            'name' => 'parent_id',
            'type' => 'id',
            'group' => 'parent_name',
            'reportable' => false,
            'vname' => 'LBL_ORIGIN_PARENT_ID',
        ),
        'target_parent_type' =>
        array(
            'name' => 'target_parent_type',
            'vname' => 'LBL_TARGET_PARENT_NAME',
            'type' => 'target_parent_type',
            'dbType' => 'varchar',
            'group' => 'target_parent_name',
            'options' => 'target_parent_type_survey_display',
            'required' => false,
            'len' => '255',
            'comment' => 'The Sugar object to which the call is related',
            'studio' => array('wirelesslistview' => false),
        ),
        'target_parent_name' =>
        array(
            'name' => 'target_parent_name',
            'parent_type' => 'record_type_display',
            'type_name' => 'target_parent_type',
            'id_name' => 'target_parent_id',
            'vname' => 'LBL_TARGET_LIST_RELATED_TO',
            'type' => 'target_parent',
            'group' => 'target_parent_name',
            'source' => 'non-db',
            'options' => 'target_parent_type_survey_display',
            'studio' => true,
        ),
        'target_parent_id' =>
        array(
            'name' => 'target_parent_id',
            'type' => 'id',
            'group' => 'target_parent_name',
            'reportable' => false,
            'vname' => 'LBL_TARGET_PARENT_ID',
        ),
        'accounts' => array(
            'name' => 'accounts',
            'type' => 'link',
            'relationship' => 'bc_survey_submission_accounts',
            'source' => 'non-db',
            'vname' => 'LBL_ACCOUNT',
        ),
        'contacts' => array(
            'name' => 'contacts',
            'type' => 'link',
            'relationship' => 'bc_survey_submission_contacts',
            'source' => 'non-db',
            'vname' => 'LBL_CONTACT',
        ),
        'leads' => array(
            'name' => 'leads',
            'type' => 'link',
            'relationship' => 'bc_survey_submission_leads',
            'source' => 'non-db',
            'vname' => 'LBL_LEAD',
        ),
        'prospects' => array(
            'name' => 'prospects',
            'type' => 'link',
            'relationship' => 'bc_survey_submission_prospects',
            'source' => 'non-db',
            'vname' => 'LBL_PROSPECT',
        ),
        'assigned_user_id' =>
        array(
            'name' => 'assigned_user_id',
            'vname' => 'LBL_ASSIGNED_TO_ID',
            'group' => 'assigned_user_name',
            'type' => 'id',
            'reportable' => false,
            'isnull' => 'false',
            'audited' => true,
            'duplicate_on_record_copy' => 'always',
            'comment' => 'User ID assigned to record',
            'duplicate_merge' => 'disabled',
            'mandatory_fetch' => true,
            'massupdate' => false,
        ),
        'assigned_user_name' =>
        array(
            'name' => 'assigned_user_name',
            'link' => 'assigned_user_link',
            'vname' => 'LBL_ASSIGNED_TO',
            'rname' => 'full_name',
            'type' => 'relate',
            'reportable' => false,
            'source' => 'non-db',
            'table' => 'users',
            'id_name' => 'assigned_user_id',
            'module' => 'Users',
            'duplicate_merge' => 'disabled',
            'duplicate_on_record_copy' => 'always',
            'sort_on' =>
            array(
                0 => 'last_name',
            ),
            'exportable' => true,
        ),
        'assigned_user_link' =>
        array(
            'name' => 'assigned_user_link',
            'type' => 'link',
            'relationship' => 'accounts_assigned_user',
            'vname' => 'LBL_ASSIGNED_TO_USER',
            'link_type' => 'one',
            'module' => 'Users',
            'bean_name' => 'User',
            'source' => 'non-db',
            'duplicate_merge' => 'enabled',
            'id_name' => 'assigned_user_id',
            'table' => 'users',
        ),
        'team_id' =>
        array(
            'name' => 'team_id',
            'vname' => 'LBL_TEAM_ID',
            'group' => 'team_name',
            'reportable' => false,
            'dbType' => 'id',
            'type' => 'team_list',
            'audited' => true,
            'duplicate_on_record_copy' => 'always',
            'comment' => 'Team ID for the account',
        ),
        'team_set_id' =>
        array(
            'name' => 'team_set_id',
            'rname' => 'id',
            'id_name' => 'team_set_id',
            'vname' => 'LBL_TEAM_SET_ID',
            'type' => 'id',
            'audited' => true,
            'studio' => 'false',
            'dbType' => 'id',
            'duplicate_on_record_copy' => 'always',
            'full_text_search' =>
            array(
                'enabled' => true,
            ),
        ),
        'submission_type' =>
        array(
            'required' => false,
            'name' => 'submission_type',
            'vname' => 'LBL_SUBMISSION_TYPE',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
        ),
        'submission_ip_address' =>
        array(
            'required' => false,
            'name' => 'submission_ip_address',
            'vname' => 'LBL_SUBMISSION_IP_ADDRESS',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
        ),
        'submission_language' =>
        array(
            'required' => false,
            'name' => 'submission_language',
            'vname' => 'LBL_SUBMISSION_LANGUAGE',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
    ),
        'new_record_id' =>
        array(
            'required' => false,
            'name' => 'new_record_id',
            'vname' => 'LBL_NEW_RECORD_ID',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
    ),
        'consent_accepted' =>
        array(
            'required' => false,
            'name' => 'consent_accepted',
            'vname' => 'LBL_CONSENT_ACCEPTED',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '0',
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
    ),
        'survey_trackdatetime' =>
        array(
            'required' => false,
            'name' => 'survey_trackdatetime',
            'vname' => 'LBL_SURVEY_TRACKDATETIME',
            'type' => 'datetimecombo',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => false,
            'dbType' => 'datetime',
    ),
        'survey_trackdatetime_temp' =>
        array(
            'required' => false,
            'name' => 'survey_trackdatetime_temp',
            'vname' => 'survey_trackdatetime_temp',
            'type' => 'datetimecombo',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => false,
            'dbType' => 'datetime',
    ),
    ),
    'relationships' => array(
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('bc_survey_submission', 'bc_survey_submission', array('basic', 'team_security', 'assignable'));
