<?php

/* This file was generated by the 7_FixIconNameChanges upgrader */
$viewdefs['UNI_condiciones_iniciales']['base']['menu']['header'] =  array (
  0 => 
  array (
    'route' => '#UNI_condiciones_iniciales/create',
    'label' => 'LNK_NEW_RECORD',
    'acl_action' => 'create',
    'acl_module' => 'UNI_condiciones_iniciales',
    'icon' => 'fa-plus',
  ),
  1 => 
  array (
    'route' => '#UNI_condiciones_iniciales',
    'label' => 'LNK_LIST',
    'acl_action' => 'list',
    'acl_module' => 'UNI_condiciones_iniciales',
    'icon' => 'fa-bars',
  ),
  2 => 
  array (
    'route' => '#bwc/index.php?module=Import&action=Step1&import_module=UNI_condiciones_iniciales&return_module=UNI_condiciones_iniciales&return_action=index',
    'label' => 'LBL_IMPORT',
    'acl_action' => 'import',
    'acl_module' => 'UNI_condiciones_iniciales',
    'icon' => 'fa-upload',
  ),
);
