<?php

/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

$dictionary['uni_Productos'] = array(
    'table' => 'uni_productos',
    'audited' => true,
    'activity_enabled' => false,
    'duplicate_merge' => true,
    'fields' => array (
  'tipo_producto' => 
  array (
    'required' => false,
    'name' => 'tipo_producto',
    'vname' => 'LBL_TIPO_PRODUCTO',
    'type' => 'enum',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '1',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'tipo_producto_list',
    'dependency' => false,
  ),
  'no_viable_razon' => 
  array (
    'required' => false,
    'name' => 'no_viable_razon',
    'vname' => 'LBL_NO_VIABLE_RAZON',
    'type' => 'enum',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '0',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'razones_ddw_list',
    'dependency' => false,
  ),
  'no_viable_razon_fp' => 
  array (
    'required' => false,
    'name' => 'no_viable_razon_fp',
    'vname' => 'LBL_NO_VIABLE_RAZON_FP',
    'type' => 'enum',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '0',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'fuera_de_perfil_ddw_list',
    'dependency' => false,
  ),
  'no_viable_razon_cf' => 
  array (
    'required' => false,
    'name' => 'no_viable_razon_cf',
    'vname' => 'LBL_NO_VIABLE_RAZON_CF',
    'type' => 'enum',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '0',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'razones_cf_list',
    'dependency' => false,
  ),
  'no_viable_producto' => 
  array (
    'required' => false,
    'name' => 'no_viable_producto',
    'vname' => 'LBL_NO_VIABLE_PRODUCTO',
    'type' => 'enum',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '0',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'no_producto_requiere_list',
    'dependency' => false,
  ),
  'no_viable_razon_ni' => 
  array (
    'required' => false,
    'name' => 'no_viable_razon_ni',
    'vname' => 'LBL_NO_VIABLE_RAZON_NI',
    'type' => 'enum',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '0',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'razones_cf_list',
    'dependency' => false,
  ),
  'tipo_cuenta' => 
  array (
    'required' => false,
    'name' => 'tipo_cuenta',
    'vname' => 'LBL_TIPO_CUENTA',
    'type' => 'enum',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '0',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'product_tipo_cuenta_list',
    'dependency' => false,
  ),
  'subtipo_cuenta' => 
  array (
    'required' => false,
    'name' => 'subtipo_cuenta',
    'vname' => 'LBL_SUBTIPO_CUENTA',
    'type' => 'enum',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '0',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'product_subtipo_cuenta_list',
    'dependency' => false,
    'visibility_grid' => 
    array (
      'trigger' => 'tipo_cuenta',
      'values' => 
      array (
        0 => 
        array (
        ),
        1 => 
        array (
          0 => '13',
          1 => '14',
        ),
        2 => 
        array (
          0 => '1',
          1 => '2',
          2 => '3',
          3 => '4',
          4 => '9',
        ),
        3 => 
        array (
          0 => '12',
          1 => '5',
          2 => '6',
          3 => '7',
          4 => '8',
          5 => '10',
          6 => '11',
          7 => '15',
          8 => '16',
          9 => '17',
          10 => '18',
        ),
        4 => 
        array (
        ),
        5 => 
        array (
        ),
      ),
    ),
  ),
  'nps_calificacion' => 
  array (
    'required' => false,
    'name' => 'nps_calificacion',
    'vname' => 'LBL_NPS_CALIFICACION',
    'type' => 'enum',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '0',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'product_nivel_satisfaccion_list',
    'dependency' => false,
  ),
  'estatus_atencion' => 
  array (
    'required' => false,
    'name' => 'estatus_atencion',
    'vname' => 'LBL_ESTATUS_ATENCION',
    'type' => 'enum',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '0',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'product_status_atencion_list',
    'dependency' => false,
  ),
  'no_viable_quien' => 
  array (
    'required' => false,
    'name' => 'no_viable_quien',
    'vname' => 'LBL_NO_VIABLE_QUIEN',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'no_viable_porque' => 
  array (
    'required' => false,
    'name' => 'no_viable_porque',
    'vname' => 'LBL_NO_VIABLE_PORQUE',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tipo_subtipo_cuenta' => 
  array (
    'required' => false,
    'name' => 'tipo_subtipo_cuenta',
    'vname' => 'LBL_TIPO_SUBTIPO_CUENTA',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'nps_comentario' => 
  array (
    'required' => false,
    'name' => 'nps_comentario',
    'vname' => 'LBL_NPS_COMENTARIO',
    'type' => 'text',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'no_viable' => 
  array (
    'required' => false,
    'name' => 'no_viable',
    'vname' => 'LBL_NO_VIABLE',
    'type' => 'bool',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => false,
    'calculated' => false,
    'size' => '20',
  ),
  'monto_impago' => 
  array (
    'required' => false,
    'name' => 'monto_impago',
    'vname' => 'LBL_MONTO_IMPAGO',
    'type' => 'currency',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => 0.0,
    'calculated' => false,
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
    'related_fields' => 
    array (
      0 => 'currency_id',
      1 => 'base_rate',
    ),
  ),
  'currency_id' => 
  array (
    'required' => false,
    'name' => 'currency_id',
    'vname' => 'LBL_CURRENCY_ID',
    'type' => 'currency_id',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => 1,
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'calculated' => false,
    'len' => 36,
    'size' => '20',
    'dbType' => 'id',
    'studio' => false,
    'function' => 'getCurrencies',
    'function_bean' => 'Currencies',
  ),
  'base_rate' => 
  array (
    'required' => false,
    'name' => 'base_rate',
    'vname' => 'LBL_CURRENCY_RATE',
    'type' => 'decimal',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => 1,
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'calculated' => false,
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
    'label' => 'LBL_CURRENCY_RATE',
    'studio' => false,
  ),
  'anexos_activos' => 
  array (
    'required' => false,
    'name' => 'anexos_activos',
    'vname' => 'LBL_ANEXOS_ACTIVOS',
    'type' => 'int',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'len' => '11',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
  ),
  'anexos_historicos' => 
  array (
    'required' => false,
    'name' => 'anexos_historicos',
    'vname' => 'LBL_ANEXOS_HISTORICOS',
    'type' => 'int',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'len' => '11',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
  ),
  'fecha_pago' => 
  array (
    'required' => false,
    'name' => 'fecha_pago',
    'vname' => 'LBL_FECHA_PAGO',
    'type' => 'date',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'calculated' => false,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'fecha_termino' => 
  array (
    'required' => false,
    'name' => 'fecha_termino',
    'vname' => 'LBL_FECHA_TERMINO',
    'type' => 'date',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'calculated' => false,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'fecha_impago' => 
  array (
    'required' => false,
    'name' => 'fecha_impago',
    'vname' => 'LBL_FECHA_IMPAGO',
    'type' => 'date',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'calculated' => false,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'fecha_liberacion' => 
  array (
    'required' => false,
    'name' => 'fecha_liberacion',
    'vname' => 'LBL_FECHA_LIBERACION',
    'type' => 'date',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'calculated' => false,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'nps_fecha' => 
  array (
    'required' => false,
    'name' => 'nps_fecha',
    'vname' => 'LBL_NPS_FECHA',
    'type' => 'date',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'calculated' => false,
    'size' => '20',
    'enable_range_search' => false,
  ),
),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
    'full_text_search' => true,
);

if (!class_exists('VardefManager')){
}
VardefManager::createVardef('uni_Productos','uni_Productos', array('basic','team_security','assignable','taggable'));