<?php

/* This file was generated by the 7_FixIconNameChanges upgrader */
$viewdefs['dire_Pais']['base']['menu']['header'] =  array (
  0 => 
  array (
    'route' => '#dire_Pais/create',
    'label' => 'LNK_NEW_RECORD',
    'acl_action' => 'create',
    'acl_module' => 'dire_Pais',
    'icon' => 'fa-plus',
  ),
  1 => 
  array (
    'route' => '#dire_Pais',
    'label' => 'LNK_LIST',
    'acl_action' => 'list',
    'acl_module' => 'dire_Pais',
    'icon' => 'fa-bars',
  ),
  2 => 
  array (
    'route' => '#bwc/index.php?module=Import&action=Step1&import_module=dire_Pais&return_module=dire_Pais&return_action=index',
    'label' => 'LBL_IMPORT',
    'acl_action' => 'import',
    'acl_module' => 'dire_Pais',
    'icon' => 'fa-upload',
  ),
);
