<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN S_seguros
 */


class S_seguros_sugar extends Basic {
    public $new_schema = true;
    public $module_dir = 'S_seguros';
    public $object_name = 'S_seguros';
    public $table_name = 's_seguros';
    public $importable = false;
    public $team_id;
    public $team_set_id;
    public $acl_team_set_id;
    public $team_count;
    public $team_name;
    public $acl_team_names;
    public $team_link;
    public $team_count_link;
    public $teams;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $tag;
    public $tag_link;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $activities;
    public $following;
    public $following_link;
    public $my_favorite;
    public $favorite_link;
    public $commentlog;
    public $commentlog_link;
    public $locked_fields;
    public $locked_fields_link;
    public $tipo;
    public $created;
    public $user_id_c;
    public $ejecutivo;
    public $tipo_referenciador;
    public $user_id1_c;
    public $referenciador;
    public $region;
    public $etapa;
    public $area;
    public $prima_obj;
    public $currency_id;
    public $base_rate;
    public $tipo_cambio_obj;
    public $info_actual;
    public $prima_neta;
    public $compania;
    public $forma_pago_act;
    public $siniestralidad;
    public $fecha_ini;
    public $fecha_fin;
    public $fecha_req;
    public $forma_pago;
    public $incentivo;
    public $ingreso_inc;
    public $ingreso_ref;
    public $id_salesforce;
    public $tipo_cambio_n;
    
    public function bean_implements($interface){
        switch($interface){
            case 'ACL': return true;
        }
        return false;
    }
    
}