<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN pmse_BpmActivityDefinition
 */
class pmse_BpmActivityDefinition_sugar extends Basic
{
    public $new_schema = true;
    public $module_dir = 'pmse_Project/pmse_BpmActivityDefinition';
    public $module_name = 'pmse_BpmActivityDefinition';
    public $object_name = 'pmse_BpmActivityDefinition';
    public $table_name = 'pmse_bpm_activity_definition';
    public $importable = false;
    public $disable_custom_fields = true;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $activities;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $pro_id;
    public $act_type;
    public $act_duration;
    public $act_duration_unit;
    public $act_send_notification;
    public $act_assignment_method;
    public $act_assign_team;
    public $act_assign_user;
    public $act_value_based_assignment;
    public $act_reassign;
    public $act_reassign_team;
    public $act_adhoc;
    public $act_adhoc_behavior;
    public $act_adhoc_team;
    public $act_response_buttons;
    public $act_last_user_assigned;
    public $act_field_module;
    public $act_fields;
    public $act_readonly_fields;
    public $act_expected_time;
    public $act_required_fields;
    public $act_related_modules;
    public $act_service_url;
    public $act_service_params;
    public $act_service_method;
    public $act_update_record_owner;
    public $execution_mode;
    public $act_email_process_user;
    public $act_email_template_id;


    public function __construct()
    {
        parent::__construct();
    }
}
