<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN TCT1_P_Fideicomiso
 */


class TCT1_P_Fideicomiso_sugar extends Basic {
    public $new_schema = true;
    public $module_dir = 'TCT1_P_Fideicomiso';
    public $object_name = 'TCT1_P_Fideicomiso';
    public $table_name = 'tct1_p_fideicomiso';
    public $importable = true;
    public $team_id;
    public $team_set_id;
    public $team_count;
    public $team_name;
    public $team_link;
    public $team_count_link;
    public $teams;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $doc_owner;
    public $user_favorites;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $activities;
    public $following;
    public $following_link;
    public $my_favorite;
    public $favorite_link;
    public $tct_ocupacion_txf;
    public $tct_fecha_nacimiento_dat;
    public $tct_genero_ddw;
    public $tct_pais_nacimiento_txf;
    public $tct_nacionalidad_txf;
    public $tct_rfc_txf;
    public $tct_no_serie_firma_txf;
    public $tct_curp_txf;
    public $tct_correo_electronico_txf;
    public $tct_telefono_tel;
    public $tct_domicilio_txf;
    public $tct_calle_txf;
    public $tct_num_interior_txf;
    public $tct_num_exterior_txf;
    public $tct_colonia_txf;
    public $tct_delegacion_txf;
    public $tct_ciudad_txf;
    public $tct_codigo_postal_txf;
    public $tct_entidad_federativa_txf;
    public $tct_pais_txf;
    public $tct_preg_v_ddw;
    public $tct_preg_w_ddw;
    public $tct_tipo_ddw;
    public $tct_regimen_fiscal_ddw;
    public $tct_cargo_publico_txf;
    public $tct_dependencia_txf;
    public $tct_periodo_txf;
    public $tct_fecha_inicio_dat;
    public $tct_fecha_termino_dat;
    public $tct_especificar_parentsco_txf;
    public $tct_nombre_persona_puesto_txf;
    public $tct_nombre_socio_txf;
    public $tct_nombre_accionista_rel_txf;
    public $tct_cargo_publico_fam_txf;
    public $tct_dependencia_fam_txf;
    public $tct_periodo_fam_txf;
    public $tct_fecha_inicio_fam_dat;
    public $tct_fecha_termino_fam_dat;
    
    /**
     * This is a deprecated method, please start using __construct() as this
     * method will be removed in a future version.
     *
     * @see __construct
     * @deprecated
     */
    public function TCT1_P_Fideicomiso_sugar(){
        $GLOBALS['log']->deprecated('Calls to TCT1_P_Fideicomiso::TCT1_P_Fideicomiso are deprecated.');
        self::__construct();
    }

    public function __construct(){
        parent::__construct();
    }
    
    public function bean_implements($interface){
        switch($interface){
            case 'ACL': return true;
        }
        return false;
    }
    
}