<?php

/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

$dictionary['TCT1_P_Fideicomiso'] = array(
    'table' => 'tct1_p_fideicomiso',
    'audited' => true,
    'activity_enabled' => false,
    'duplicate_merge' => true,
    'fields' => array (
  'tct_ocupacion_txf' => 
  array (
    'required' => false,
    'name' => 'tct_ocupacion_txf',
    'vname' => 'LBL_TCT_OCUPACION_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tct_fecha_nacimiento_dat' => 
  array (
    'required' => false,
    'name' => 'tct_fecha_nacimiento_dat',
    'vname' => 'LBL_TCT_FECHA_NACIMIENTO_DAT',
    'type' => 'date',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'size' => '20',
    'enable_range_search' => false,
  ),
  'tct_genero_ddw' => 
  array (
    'required' => false,
    'name' => 'tct_genero_ddw',
    'vname' => 'LBL_TCT_GENERO_DDW',
    'type' => 'enum',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'genero_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'tct_pais_nacimiento_txf' => 
  array (
    'required' => false,
    'name' => 'tct_pais_nacimiento_txf',
    'vname' => 'LBL_TCT_PAIS_NACIMIENTO_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tct_nacionalidad_txf' => 
  array (
    'required' => false,
    'name' => 'tct_nacionalidad_txf',
    'vname' => 'LBL_TCT_NACIONALIDAD_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tct_rfc_txf' => 
  array (
    'required' => false,
    'name' => 'tct_rfc_txf',
    'vname' => 'LBL_TCT_RFC_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tct_no_serie_firma_txf' => 
  array (
    'required' => false,
    'name' => 'tct_no_serie_firma_txf',
    'vname' => 'LBL_TCT_NO_SERIE_FIRMA_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tct_curp_txf' => 
  array (
    'required' => false,
    'name' => 'tct_curp_txf',
    'vname' => 'LBL_TCT_CURP_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tct_correo_electronico_txf' => 
  array (
    'required' => false,
    'name' => 'tct_correo_electronico_txf',
    'vname' => 'LBL_TCT_CORREO_ELECTRONICO_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tct_telefono_tel' => 
  array (
    'required' => false,
    'name' => 'tct_telefono_tel',
    'vname' => 'LBL_TCT_TELEFONO_TEL',
    'type' => 'phone',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
  ),
  'tct_domicilio_txf' => 
  array (
    'required' => false,
    'name' => 'tct_domicilio_txf',
    'vname' => 'LBL_TCT_DOMICILIO_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tct_calle_txf' => 
  array (
    'required' => false,
    'name' => 'tct_calle_txf',
    'vname' => 'LBL_TCT_CALLE_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tct_num_interior_txf' => 
  array (
    'required' => false,
    'name' => 'tct_num_interior_txf',
    'vname' => 'LBL_TCT_NUM_INTERIOR_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tct_num_exterior_txf' => 
  array (
    'required' => false,
    'name' => 'tct_num_exterior_txf',
    'vname' => 'LBL_TCT_NUM_EXTERIOR_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tct_colonia_txf' => 
  array (
    'required' => false,
    'name' => 'tct_colonia_txf',
    'vname' => 'LBL_TCT_COLONIA_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tct_delegacion_txf' => 
  array (
    'required' => false,
    'name' => 'tct_delegacion_txf',
    'vname' => 'LBL_TCT_DELEGACION_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tct_ciudad_txf' => 
  array (
    'required' => false,
    'name' => 'tct_ciudad_txf',
    'vname' => 'LBL_TCT_CIUDAD_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tct_codigo_postal_txf' => 
  array (
    'required' => false,
    'name' => 'tct_codigo_postal_txf',
    'vname' => 'LBL_TCT_CODIGO_POSTAL_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tct_entidad_federativa_txf' => 
  array (
    'required' => false,
    'name' => 'tct_entidad_federativa_txf',
    'vname' => 'LBL_TCT_ENTIDAD_FEDERATIVA_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tct_pais_txf' => 
  array (
    'required' => false,
    'name' => 'tct_pais_txf',
    'vname' => 'LBL_TCT_PAIS_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'tct_preg_v_ddw' => 
  array (
    'required' => false,
    'name' => 'tct_preg_v_ddw',
    'vname' => 'LBL_TCT_PREG_V_DDW',
    'type' => 'enum',
    'massupdate' => true,
    'default' => 'No',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'tct_fedeicomiso_si_no_ddw_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'tct_preg_w_ddw' => 
  array (
    'required' => false,
    'name' => 'tct_preg_w_ddw',
    'vname' => 'LBL_TCT_PREG_W_DDW',
    'type' => 'enum',
    'massupdate' => true,
    'default' => 'No',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'tct_fedeicomiso_si_no_ddw_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'tct_tipo_ddw' => 
  array (
    'required' => true,
    'name' => 'tct_tipo_ddw',
    'vname' => 'LBL_TCT_TIPO_DDW',
    'type' => 'enum',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'tct_tipo_ddw_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'name' => 
  array (
    'name' => 'name',
    'vname' => 'LBL_NAME',
    'type' => 'name',
    'link' => true,
    'dbType' => 'varchar',
    'len' => '255',
    'unified_search' => true,
    'full_text_search' => 
    array (
      'boost' => '3',
      'enabled' => true,
    ),
    'required' => true,
    'importable' => 'required',
    'duplicate_merge' => 'enabled',
    'merge_filter' => 'selected',
    'duplicate_on_record_copy' => 'always',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'duplicate_merge_dom_value' => '3',
    'audited' => false,
    'reportable' => true,
    'calculated' => false,
    'size' => '20',
  ),
  'tct_regimen_fiscal_ddw' => 
  array (
    'required' => false,
    'name' => 'tct_regimen_fiscal_ddw',
    'vname' => 'LBL_TCT_REGIMEN_FISCAL_DDW',
    'type' => 'enum',
    'massupdate' => true,
    'default' => 'Persona Fisica',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'tipo',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'tct_cargo_publico_txf' => 
  array (
    'required' => false,
    'name' => 'tct_cargo_publico_txf',
    'vname' => 'LBL_TCT_CARGO_PUBLICO_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'dependency' => 'equal($tct_preg_v_ddw,"Si")',
  ),
  'tct_dependencia_txf' => 
  array (
    'required' => false,
    'name' => 'tct_dependencia_txf',
    'vname' => 'LBL_TCT_DEPENDENCIA_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'dependency' => 'equal($tct_preg_v_ddw,"Si")',
  ),
  'tct_periodo_txf' => 
  array (
    'required' => false,
    'name' => 'tct_periodo_txf',
    'vname' => 'LBL_TCT_PERIODO_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'dependency' => 'equal($tct_preg_v_ddw,"Si")',
  ),
  'tct_fecha_inicio_dat' => 
  array (
    'required' => false,
    'name' => 'tct_fecha_inicio_dat',
    'vname' => 'LBL_TCT_FECHA_INICIO_DAT',
    'type' => 'date',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'size' => '20',
    'enable_range_search' => false,
    'dependency' => 'equal($tct_preg_v_ddw,"Si")',
  ),
  'tct_fecha_termino_dat' => 
  array (
    'required' => false,
    'name' => 'tct_fecha_termino_dat',
    'vname' => 'LBL_TCT_FECHA_TERMINO_DAT',
    'type' => 'date',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'size' => '20',
    'enable_range_search' => false,
    'dependency' => 'equal($tct_preg_v_ddw,"Si")',
  ),
  'tct_especificar_parentsco_txf' => 
  array (
    'required' => false,
    'name' => 'tct_especificar_parentsco_txf',
    'vname' => 'LBL_TCT_ESPECIFICAR_PARENTSCO_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'dependency' => 'equal($tct_preg_w_ddw,"Si")',
  ),
  'tct_nombre_persona_puesto_txf' => 
  array (
    'required' => false,
    'name' => 'tct_nombre_persona_puesto_txf',
    'vname' => 'LBL_TCT_NOMBRE_PERSONA_PUESTO_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'dependency' => 'equal($tct_preg_w_ddw,"Si")',
  ),
  'tct_nombre_socio_txf' => 
  array (
    'required' => false,
    'name' => 'tct_nombre_socio_txf',
    'vname' => 'LBL_TCT_NOMBRE_SOCIO_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'dependency' => 'and(equal($tct_preg_v_ddw,"Si"),equal($tct_regimen_fiscal_ddw,"Persona Moral"))',
  ),
  'tct_nombre_accionista_rel_txf' => 
  array (
    'required' => false,
    'name' => 'tct_nombre_accionista_rel_txf',
    'vname' => 'LBL_TCT_NOMBRE_ACCIONISTA_REL_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'dependency' => 'and(equal($tct_preg_w_ddw,"Si"),equal($tct_regimen_fiscal_ddw,"Persona Moral"))',
  ),
  'tct_cargo_publico_fam_txf' => 
  array (
    'required' => false,
    'name' => 'tct_cargo_publico_fam_txf',
    'vname' => 'LBL_TCT_CARGO_PUBLICO_FAM_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'dependency' => 'equal($tct_preg_w_ddw,"Si")',
  ),
  'tct_dependencia_fam_txf' => 
  array (
    'required' => false,
    'name' => 'tct_dependencia_fam_txf',
    'vname' => 'LBL_TCT_DEPENDENCIA_FAM_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'dependency' => 'equal($tct_preg_w_ddw,"Si")',
  ),
  'tct_periodo_fam_txf' => 
  array (
    'required' => false,
    'name' => 'tct_periodo_fam_txf',
    'vname' => 'LBL_TCT_PERIODO_FAM_TXF',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'full_text_search' => 
    array (
      'boost' => '0',
      'enabled' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'dependency' => 'equal($tct_preg_w_ddw,"Si")',
  ),
  'tct_fecha_inicio_fam_dat' => 
  array (
    'required' => false,
    'name' => 'tct_fecha_inicio_fam_dat',
    'vname' => 'LBL_TCT_FECHA_INICIO_FAM_DAT',
    'type' => 'date',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'size' => '20',
    'enable_range_search' => false,
    'dependency' => 'equal($tct_preg_w_ddw,"Si")',
  ),
  'tct_fecha_termino_fam_dat' => 
  array (
    'required' => false,
    'name' => 'tct_fecha_termino_fam_dat',
    'vname' => 'LBL_TCT_FECHA_TERMINO_FAM_DAT',
    'type' => 'date',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'size' => '20',
    'enable_range_search' => false,
    'dependency' => 'equal($tct_preg_w_ddw,"Si")',
  ),
),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
);

if (!class_exists('VardefManager')){
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('TCT1_P_Fideicomiso','TCT1_P_Fideicomiso', array('basic','team_security','assignable'));