<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN pmse_BpmRelatedDependency
 */
class pmse_BpmRelatedDependency_sugar extends Basic
{
    public $new_schema = true;
    public $module_dir = 'pmse_Project/pmse_BpmRelatedDependency';
    public $module_name = 'pmse_BpmRelatedDependency';
    public $object_name = 'pmse_BpmRelatedDependency';
    public $table_name = 'pmse_bpm_related_dependency';
    public $importable = false;
    public $disable_custom_fields = true;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $activities;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $evn_id;
    public $evn_uid;
    public $evn_marker;
    public $evn_is_interrupting;
    public $evn_attached_to;
    public $evn_cancel_activity;
    public $evn_activity_ref;
    public $evn_wait_for_completion;
    public $evn_error_name;
    public $evn_error_code;
    public $evn_escalation_name;
    public $evn_escalation_code;
    public $evn_condition;
    public $evn_message;
    public $evn_operation_name;
    public $evn_operation_implementation;
    public $evn_time_date;
    public $evn_time_cycle;
    public $evn_time_duration;
    public $evn_behavior;
    public $evn_status;
    public $evn_type;
    public $evn_module;
    public $evn_criteria;
    public $evn_params;
    public $evn_script;
    public $prj_id;
    public $pro_id;
    public $pro_module;
    public $pro_status;
    public $pro_locked_variables;
    public $pro_terminate_variables;
    public $rel_element_id;
    public $rel_element_type;
    public $rel_process_module;
    public $rel_element_module;
    public $rel_element_relationship;


    public function __construct()
    {
        parent::__construct();
    }
}
