<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
$vardefs = array (
  'fields' => 
  array (
    'no_backlog' => 
    array (
      'required' => false,
      'readonly' => true,
      'name' => 'no_backlog',
      'vname' => 'LBL_NO_BACKLOG',
      'type' => 'autoincrement',
      'massupdate' => false,
      'hidemassupdate' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => false,
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => 1,
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'pii' => false,
      'full_text_search' => 
      array (
        'enabled' => '0',
        'boost' => '1',
        'searchable' => false,
      ),
      'calculated' => false,
      'len' => '11',
      'size' => '20',
      'enable_range_search' => false,
      'auto_increment' => 'true',
      'dbType' => 'int',
      'disable_num_format' => true,
      'auto_increment_platform_options' => 
      array (
        'unique' => true,
      ),
      'min' => 1,
      'max' => '',
      'validation' => 
      array (
        'type' => 'range',
        'min' => 1,
        'max' => '',
      ),
    ),
    'producto' => 
    array (
      'required' => false,
      'readonly' => false,
      'name' => 'producto',
      'vname' => 'LBL_PRODUCTO',
      'type' => 'enum',
      'massupdate' => true,
      'hidemassupdate' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'pii' => false,
      'default' => 'Seguros',
      'calculated' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'producto_bl_seguros_list',
      'dependency' => false,
    ),
    'tipo_negocio' => 
    array (
      'required' => true,
      'readonly' => false,
      'name' => 'tipo_negocio',
      'vname' => 'LBL_TIPO_NEGOCIO',
      'type' => 'enum',
      'massupdate' => true,
      'hidemassupdate' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'pii' => false,
      'default' => '',
      'calculated' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'tipo_negocio_bl_seguros_list',
      'dependency' => false,
    ),
    'subramo' => 
    array (
      'required' => false,
      'readonly' => false,
      'name' => 'subramo',
      'vname' => 'LBL_SUBRAMO',
      'type' => 'enum',
      'massupdate' => true,
      'hidemassupdate' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'pii' => false,
      'default' => '',
      'calculated' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'subramos_dynamics_list',
      'dependency' => false,
    ),
    'tipo_poliza' => 
    array (
      'required' => false,
      'readonly' => false,
      'name' => 'tipo_poliza',
      'vname' => 'LBL_TIPO_POLIZA',
      'type' => 'enum',
      'massupdate' => true,
      'hidemassupdate' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'pii' => false,
      'default' => '',
      'calculated' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'tipo_poliza_list',
      'dependency' => false,
    ),
    'anio' => 
    array (
      'required' => true,
      'readonly' => false,
      'name' => 'anio',
      'vname' => 'LBL_ANIO',
      'type' => 'enum',
      'massupdate' => true,
      'hidemassupdate' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'pii' => false,
      'default' => '2024',
      'calculated' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'anio_list',
      'dependency' => false,
    ),
    'mes' => 
    array (
      'required' => true,
      'readonly' => false,
      'name' => 'mes',
      'vname' => 'LBL_MES',
      'type' => 'enum',
      'massupdate' => true,
      'hidemassupdate' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'pii' => false,
      'default' => '',
      'calculated' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'mes_list',
      'dependency' => false,
    ),
    'tipo_operacion' => 
    array (
      'required' => true,
      'readonly' => false,
      'name' => 'tipo_operacion',
      'vname' => 'LBL_TIPO_OPERACION',
      'type' => 'enum',
      'massupdate' => true,
      'hidemassupdate' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'pii' => false,
      'default' => '',
      'calculated' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'tipo_operacion_bl_seguros_list',
      'dependency' => false,
    ),
    'user_id_c' => 
    array (
      'required' => false,
      'readonly' => false,
      'name' => 'user_id_c',
      'vname' => 'LBL_REFERENCIADOR_USER_ID',
      'type' => 'id',
      'massupdate' => false,
      'hidemassupdate' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => 1,
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'pii' => false,
      'calculated' => false,
      'len' => 36,
      'size' => '20',
    ),
    'referenciador' => 
    array (
      'required' => false,
      'readonly' => false,
      'source' => 'non-db',
      'name' => 'referenciador',
      'vname' => 'LBL_REFERENCIADOR',
      'type' => 'relate',
      'massupdate' => true,
      'hidemassupdate' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'pii' => false,
      'calculated' => false,
      'len' => 255,
      'size' => '20',
      'id_name' => 'user_id_c',
      'ext2' => 'Users',
      'module' => 'Users',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'user_id1_c' => 
    array (
      'required' => false,
      'readonly' => false,
      'name' => 'user_id1_c',
      'vname' => 'LBL_DIRECTOR_EQUIPO_USER_ID',
      'type' => 'id',
      'massupdate' => false,
      'hidemassupdate' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => 1,
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'pii' => false,
      'calculated' => false,
      'len' => 36,
      'size' => '20',
    ),
    'director_equipo' => 
    array (
      'required' => false,
      'readonly' => false,
      'source' => 'non-db',
      'name' => 'director_equipo',
      'vname' => 'LBL_DIRECTOR_EQUIPO',
      'type' => 'relate',
      'massupdate' => true,
      'hidemassupdate' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'pii' => false,
      'calculated' => false,
      'len' => 255,
      'size' => '20',
      'id_name' => 'user_id1_c',
      'ext2' => 'Users',
      'module' => 'Users',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'estimado_prima_neta_objetivo' => 
    array (
      'required' => false,
      'readonly' => false,
      'name' => 'estimado_prima_neta_objetivo',
      'vname' => 'LBL_ESTIMADO_PRIMA_NETA_OBJETIVO',
      'type' => 'currency',
      'massupdate' => false,
      'hidemassupdate' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'pii' => false,
      'default' => 0.0,
      'calculated' => false,
      'len' => 26,
      'size' => '20',
      'enable_range_search' => false,
      'convertToBase' => true,
      'showTransactionalAmount' => true,
      'precision' => 6,
      'related_fields' => 
      array (
        0 => 'currency_id',
        1 => 'base_rate',
      ),
    ),
    'currency_id' => 
    array (
      'required' => false,
      'readonly' => false,
      'name' => 'currency_id',
      'vname' => 'LBL_CURRENCY_ID',
      'type' => 'currency_id',
      'massupdate' => false,
      'hidemassupdate' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => 1,
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'pii' => false,
      'calculated' => false,
      'len' => 36,
      'size' => '20',
      'dbType' => 'id',
      'studio' => false,
      'function' => 'getCurrencies',
      'function_bean' => 'Currencies',
    ),
    'base_rate' => 
    array (
      'required' => false,
      'readonly' => false,
      'name' => 'base_rate',
      'vname' => 'LBL_CURRENCY_RATE',
      'type' => 'decimal',
      'massupdate' => true,
      'hidemassupdate' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => 1,
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'pii' => false,
      'calculated' => false,
      'len' => 26,
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
      'label' => 'LBL_CURRENCY_RATE',
      'studio' => false,
    ),
    'estimado_prima_total_objetivo' => 
    array (
      'required' => false,
      'readonly' => false,
      'name' => 'estimado_prima_total_objetivo',
      'vname' => 'LBL_ESTIMADO_PRIMA_TOTAL_OBJETIVO',
      'type' => 'currency',
      'massupdate' => false,
      'hidemassupdate' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'pii' => false,
      'default' => 0.0,
      'calculated' => false,
      'len' => 26,
      'size' => '20',
      'enable_range_search' => false,
      'convertToBase' => true,
      'showTransactionalAmount' => true,
      'precision' => 6,
      'related_fields' => 
      array (
        0 => 'currency_id',
        1 => 'base_rate',
      ),
    ),
    'fecha_entrega_cliente' => 
    array (
      'required' => false,
      'readonly' => false,
      'name' => 'fecha_entrega_cliente',
      'vname' => 'LBL_FECHA_ENTREGA_CLIENTE',
      'type' => 'date',
      'massupdate' => true,
      'hidemassupdate' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'pii' => false,
      'calculated' => false,
      'size' => '20',
      'enable_range_search' => false,
    ),
    'etapa' => 
    array (
      'required' => false,
      'readonly' => false,
      'name' => 'etapa',
      'vname' => 'LBL_ETAPA',
      'type' => 'enum',
      'massupdate' => true,
      'hidemassupdate' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'pii' => false,
      'default' => '1',
      'calculated' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'etapa_seguros_list',
      'dependency' => false,
    ),
    'asesor_vta_cruzada' => 
    array (
      'required' => false,
      'readonly' => false,
      'name' => 'asesor_vta_cruzada',
      'vname' => 'LBL_ASESOR_VTA_CRUZADA',
      'type' => 'enum',
      'massupdate' => true,
      'hidemassupdate' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'pii' => false,
      'default' => '',
      'calculated' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'asesor_bl_vta_cruzada_list',
      'dependency' => false,
    ),
  ),
  'relationships' => 
  array (
  ),
);